name: manjaro-arm64-xfce-rootfs
on: {workflow_dispatch: null, schedule: [{cron: '30 1 * * 1'}]}
env:
  EXTRA_PKGS: bash pacman glibc util-linux sed sudo systemd supervisor screen tar xz gzip ca-certificates ca-certificates-utils nano vim xorg-server xorg-xinit xorg-apps xf86-video-dummy xfce4 xfce4-goodies lightdm lightdm-gtk-greeter pavucontrol pulseaudio pulseaudio-alsa networkmanager gvfs gvfs-afc gvfs-mtp gvfs-gphoto2 ttf-dejavu ttf-liberation noto-fonts-cjk x11vnc xvfb
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions: {contents: write}
    steps:
      - uses: docker/setup-qemu-action@v3
        with: {platforms: arm64}
      - id: date
        run: echo "tag=$(date +%Y%m%d)" >>"$GITHUB_OUTPUT"
      - run: |
          docker run --rm --privileged --platform linux/arm64/v8 \
            -e EXTRA_PKGS="$EXTRA_PKGS" -e TAG="${{ steps.date.outputs.tag }}" -v "$PWD":/out \
            manjarolinux/base:latest bash -euxc '
            pacman -Sy --noconfirm arch-install-scripts
            pacman-key --init
            pacman-key --populate manjaro archlinuxarm
            mkdir -p /tmp/rootfs
            pacstrap -c -G -M /tmp/rootfs base ${EXTRA_PKGS}
            arch-chroot /tmp/rootfs /bin/bash -euxc "
              rm -f /etc/machine-id
              systemctl enable NetworkManager supervisor
              mkdir -p /etc/x11vnc
              echo 123456 | x11vnc -storepasswd /etc/x11vnc/passwd
              printf \"[supervisord]\nnodaemon=false\nuser=root\nlogfile=/var/log/supervisor.log\n[xvfb]\ncommand=/usr/bin/Xvfb :1 -screen 0 1920x1080x24 -ac -nolisten tcp\nautostart=true\nautorestart=true\nenvironment=DISPLAY=:1\n[x11vnc]\ncommand=/usr/bin/x11vnc -display :1 -forever -shared -noxdamage -rfbport 5901 -rfbauth /etc/x11vnc/passwd\nautostart=true\nautorestart=true\n[xfce-in-screen]\ncommand=/usr/bin/screen -DmS xfce /usr/bin/startxfce4\nautostart=true\nautorestart=true\nenvironment=DISPLAY=:1\n\" > /etc/supervisord.conf
              pacman -Scc --noconfirm
            "
            tar --numeric-owner -czpf /out/manjaro-arm64-xfce-${TAG}.tar.gz -C /tmp/rootfs .
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          files: manjaro-arm64-xfce-${{ steps.date.outputs.tag }}.tar.gz
          body: |
            Manjaro ARM64 rootfs with XFCE + supervisor + screen + x11vnc
            VNC 5901 password 123456
