name: manjaro-arm64-xfce4-rootfs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1'

env:
  EXTRA_PKGS: >
    util-linux sed sudo systemd supervisor tar xz gzip ca-certificates ca-certificates-utils nano vim
    xfce4 xfce4-goodies lightdm lightdm-gtk-greeter
    noto-fonts noto-fonts-cjk noto-fonts-emoji
    ttf-dejavu ttf-liberation wqy-zenhei wqy-microhei
    glmark2 mesa-demos pavucontrol pulseaudio dbus-x11
    gcc clang cmake make fakeroot-tcp base-devel go git

jobs:
  rootfs:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Generate date tag
        id: date
        run: echo "tag=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Build rootfs inside arm64 container
        run: |
          docker run --rm --privileged --platform linux/arm64/v8 \
            -e EXTRA_PKGS -e TAG="${{ steps.date.outputs.tag }}" \
            -v "$PWD":/out manjarolinux/base:latest bash -euxc '
            pacman -Sy --noconfirm arch-install-scripts
            pacman-key --init
            pacman-key --populate manjaro archlinuxarm
            mkdir -p /tmp/rootfs
            pacstrap -c -G -M /tmp/rootfs base ${EXTRA_PKGS}

            # 安装 yay-bin，然后删除临时用户
            arch-chroot /tmp/rootfs /bin/bash -euxc "
              useradd -m builder
              echo \"builder ALL=(ALL) NOPASSWD: ALL\" >> /etc/sudoers
              su - builder -c '
                git clone https://aur.archlinux.org/yay-bin.git /tmp/yay-bin
                cd /tmp/yay-bin && makepkg -si --noconfirm
              '
              pacman -U --noconfirm /tmp/yay-bin/*.pkg.tar.zst
              rm -rf /tmp/yay-bin
              userdel -r builder
            "

            # 清理
            rm -f /tmp/rootfs/etc/machine-id
            pacman -Scc --noconfirm -r /tmp/rootfs
            tar --numeric-owner -czpf /out/manjaro-arm64-xfce4-${TAG}.tar.gz -C /tmp/rootfs .
          '

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          files: manjaro-arm64-xfce4-${{ steps.date.outputs.tag }}.tar.gz
