name: manjaro-arm64-rootfs
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 1'
env:
  EXTRA_PKGS: util-linux sed sudo systemd tar xz gzip ca-certificates ca-certificates-utils nano vim screen xfce4-terminal xorg-server-xvfb x11vnc fluxbox dbus-x11 supervisor
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - id: date
        run: echo "tag=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"
      - run: |
          docker run --rm --privileged --platform linux/arm64/v8 \
            -e EXTRA_PKGS="$EXTRA_PKGS" -e TAG="${{ steps.date.outputs.tag }}" \
            -v "$PWD":/out manjarolinux/base:latest bash -euxc '
            pacman -Sy --noconfirm arch-install-scripts
            pacman-key --init && pacman-key --populate manjaro archlinuxarm
            mkdir -p /tmp/rootfs
            pacstrap -c -G -M /tmp/rootfs base ${EXTRA_PKGS}
            ln -sf /usr/share/zoneinfo/Asia/Shanghai /tmp/rootfs/etc/localtime
            VNC_PASS=$(openssl rand -base64 16)
            echo "$VNC_PASS" > /tmp/rootfs/vnc_pass.txt
            mkdir -p /tmp/rootfs/root/.vnc
            printf "%s\n%s\nn\n" "$VNC_PASS" "$VNC_PASS" | chroot /tmp/rootfs vncpasswd -f > /tmp/rootfs/root/.vnc/passwd
            chmod 600 /tmp/rootfs/root/.vnc/passwd
            # Supervisor 配置
            mkdir -p /tmp/rootfs/etc/supervisor.d
            cat > /tmp/rootfs/etc/supervisor.d/x.conf <<EOF
            [program:xvfb]
            command=Xvfb :1 -screen 0 1280x720x24 -ac +extension RANDR +extension GLX
            directory=/root
            autostart=true
            autorestart=true
            startretries=5
            priority=1
            user=root
            stdout_logfile=/var/log/supervisor/xvfb.log
            stderr_logfile=/var/log/supervisor/xvfb.log
            [program:x11vnc]
            command=x11vnc -display :1 -rfbport 5901 -forever -shared -noxdamage -xkb -rfbauth /root/.vnc/passwd
            directory=/root
            autostart=true
            autorestart=true
            startretries=3
            priority=10
            user=root
            stdout_logfile=/var/log/supervisor/x11vnc.log
            stderr_logfile=/var/log/supervisor/x11vnc.log
            [program:screen]
            command=screen -dmS vnc bash -c "DISPLAY=:1 fluxbox & xfce4-terminal"
            directory=/root
            autostart=true
            autorestart=true
            startretries=3
            priority=20
            user=root
            stdout_logfile=/var/log/supervisor/screen.log
            stderr_logfile=/var/log/supervisor/screen.log
            EOF
            # systemd 启动 Supervisor
            cat > /tmp/rootfs/etc/systemd/system/supervisor.service <<EOF
            [Unit]
            Description=Supervisor
            After=network.target
            [Service]
            Type=forking
            ExecStart=/usr/bin/supervisord -c /etc/supervisor.d/x.conf
            ExecReload=/usr/bin/supervisorctl reload
            ExecStop=/usr/bin/supervisorctl shutdown
            Restart=on-failure
            User=root
            [Install]
            WantedBy=multi-user.target
            EOF
            chroot /tmp/rootfs systemctl enable supervisor.service
            rm -f /tmp/rootfs/etc/machine-id
            pacman -Scc --noconfirm -r /tmp/rootfs
            tar --numeric-owner -czpf /out/manjaro-arm64-${TAG}.tar.gz -C /tmp/rootfs .
            '
      - uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.date.outputs.tag }}
          files: manjaro-arm64-${{ steps.date.outputs.tag }}.tar.gz
          body: |
            随机 VNC 密码：$(cat manjaro-arm64-${{ steps.date.outputs.tag }}.tar.gz | tar -xzO vnc_pass.txt)
