name: manjaro-arm64-rootfs

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 0'

permissions:
  contents: write

env:
  ARCH: aarch64
  ROOTFS_NAME: manjaro-arm64

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Timestamp
        id: ts
        run: echo "TS=$(date +%Y%m%d)" >> "$GITHUB_OUTPUT"

      - name: Install host deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            arch-install-scripts qemu-user-static binfmt-support tar xz-utils

      - name: Register qemu-user-static
        run: sudo systemctl restart systemd-binfmt

      - name: Bootstrap rootfs
        run: |
          set -xe
          WORK=$PWD/rootfs-build
          ROOTFS=$WORK/${{ env.ROOTFS_NAME }}
          sudo rm -rf "$WORK"
          mkdir -p "$ROOTFS"
          sudo cp /usr/bin/qemu-aarch64-static "$ROOTFS/usr/bin/"
          sudo pacstrap -K -M -c "$ROOTFS" \
            base systemd pacman-mirrors networkmanager nano vim busybox screen sudo \
            util-linux supervisor ca-certificates ca-certificates-utils gzip tar xz

          sudo chroot "$ROOTFS" ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo Asia/Shanghai | sudo tee "$ROOTFS/etc/timezone"
          sudo chroot "$ROOTFS" systemctl enable NetworkManager.service
          sudo mount --bind /proc "$ROOTFS/proc"
          sudo mount --bind /dev  "$ROOTFS/dev"
          sudo chroot "$ROOTFS" pacman -Scc --noconfirm
          sudo umount -l "$ROOTFS"/{proc,dev}
          sudo rm -f "$ROOTFS/usr/bin/qemu-aarch64-static"

      - name: Pack
        run: |
          ARCHIVE=${{ env.ROOTFS_NAME }}-${{ steps.ts.outputs.TS }}.tar.xz
          sudo tar -C rootfs-build -cJf "$ARCHIVE" "${{ env.ROOTFS_NAME }}"
          sudo chown "$USER:$USER" "$ARCHIVE"
          echo "ARCHIVE=$ARCHIVE" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.ts.outputs.TS }}
          name: Manjaro-ARM aarch64 ${{ steps.ts.outputs.TS }}
          files: ${{ env.ARCHIVE }}
